### ISSUE TITLE
Issue connecting to REST and gRPC servers

### ISSUE THREAD

**Issue by krook** [ibm-build-lab/Watson-NLP#18]
On some developer workstations there is a problem connecting to the REST or gRPC services after building and running images locally, resulting in the following error on the client:

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = “failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:8085: Socket closed”
	debug_error_string = “UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:8085: Socket closed
```

The cause of this seems to be that the process dies in the container server:

```
2022-12-14T22:45:20.971419 [MODEL-MANAGR:INFO:140660459217152] <COM44739400I> Loading local models into Common Service...
2022-12-14T22:45:20.971707 [MODEL-LOADER:INFO:140660459217152] <COM89711114I> Loading model 'classification_ensemble-workflow_lang_en_tone-stock'

.

.

/run_with_gateway.sh: line 13:    10 Killed                  python3 -m watson_runtime.grpc_server
```

I see this issue with an Intel Mac (both Big Sur and Monterey) using Docker Desktop (which shows the container is running and bound to the expected port). It's been reported by another user on a Mac as well.

**Comment by krook** [comment]
FYI @mjspriggs and @jaffaszt

**Comment by timroster** [comment]
@krook what is the memory size available to the container runtime? Is the container runtime based off of a VM with a default memory configuration or anything less than 8 GB?

**Comment by krook** [comment]
Interesting. Docker Desktop was throttled at 2GB. I've bumped it to 6GB. Still the same client side error, but now a lot more detail in the server side logs... standby...

![image](https://user-images.githubusercontent.com/1499840/207753191-90fe8a3f-6427-4354-a1df-45d9d998022a.png)

**Comment by krook** [comment]
So things have moved from a runtime error to an application error. The `status = StatusCode.UNAVAILABLE` is now a `status = StatusCode.UNIMPLEMENTED`. Instead of not connecting, it's just not finding the method called.

These were the settings changed in Docker Desktop:
* Resources: Memory: 10GB; Disk image size: Add more
* General: Uncheck "Use gRPC FUSE for file sharing". When I killed what was on port 8085, it brought down Docker Desktop, not the container.

**Comment by krook** [comment]
The above settings fixed the issue for the alternative REST API documented here: https://medium.com/ibm-data-ai/get-started-with-serving-watson-nlp-models-d760d5af553c

**Comment by krook** [comment]
Issue is resolved. @mjspriggs @htalukderibm we should see if we can add a prerequisite to step 3 here saying that the minimum memory for the container should be 8GB: https://developer.ibm.com/tutorials/serve-pretrained-models-with-a-standalone-container/
